### PR TITLE
Prevent multiple static DHCP entries with same IP

### LINKED ISSUE #889: Adding duplicate static DHCP lease information causes "service dnsmasq restart" failure
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

4

---
**Expected behaviour:**

If user attempts to add a static DHCP lease entry containing an IP address that has been previously assigned (i.e. that already exists in ```/etc/dnsmasq.d/04-pihole-static-dhcp.conf```) Pi-hole should check the static DHCP list to see if the IP address is already assigned. If it is assigned, Pi-hole should display an error message, not add the entry to the ```04-pihole-static-dhcp.conf``` file, and not attempt to restart dnsmasq.

**Actual behaviour:**

If user attempts to add a static DHCP lease entry, pi-hole accepts the entry without any scrutiny. If the entry contains an IP address or MAC address that already exists in ```/etc/dnsmasq.d/04-pihole-static-dhcp.conf```, dnsmasq fails to restart after saving the static conf file.

Pi-hold also allows duplicate MAC addresses and hostnames to be added, but duplicate MACs or hostnames in the ```/etc/dnsmasq.d/04-pihole-static-dhcp.conf``` file don't prevent dnsmasq from restarting. In a perfect world, you should probably check for dupes there as well, but the priority would be to at least make a simple attempt to compare the IP address to the existing list prior to adding it and crashing dnsmasq.

**Steps to reproduce:**

Add an entry to the DHCP static list with an IP address that's already reserved. The easiest way to do this is to pick a client from the *Currently active DHCP leases* list that's also on the *Static DHCP leases* list, press its orange button with the arrow and clipboard, then scroll down and press the green "+" icon on the new entry. This effectively "crashes" dnsmasq.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

None needed in this case.

**Troubleshooting undertaken, and/or other relevant information:**

I've now gotten into the habit of SSH-ing to my Pi-hole server after every DHCP static IP addition to manually restart dnsmasq and verify no error message. Some sort of indication in the interface that dnsmasq is running might be useful. In fact, I might try to tinker with that part myself later today in the AdminLTE repo.

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

*This PR is intentionally opened towards `release/v4.2` and not `development`*

**What does this PR aim to accomplish?:**

Prevent multiple static DHCP entries for the same IP address to get added. Fixes #889

screenshot at 2019-01-15 17-16-20

**How does this PR accomplish the above?:**

Loop over all entries in the static leases file and ensure that the entry we want to add isn't already there. The check was already there (to prevent duplicated MAC addresses) and is only extended by this PR.

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

File: scripts/pi-hole/php/savesettings.php [hunk 1]
```diff
@@ -558,6 +558,11 @@ function readAdlists()
 							$error .= "Static release for MAC address (".htmlspecialchars($mac).") already defined!<br>";
 							break;
 						}
+						if($ip !== "noip" && $lease["IP"] === $ip)
+						{
+							$error .= "Static release for IP address (".htmlspecialchars($ip).") already defined!<br>";
```
Comment (Mcat12) [inline scripts/pi-hole/php/savesettings.php]:
```suggestion
							$error .= "Static lease for IP address (".htmlspecialchars($ip).") already defined!<br>";
```

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/cant-resolve-clients-with-static-dchp-leases/16323/11
