### PR TITLE
Use non-standard location of FTL's database

### LINKED ISSUE #643: Long term DB location
**This is not an issue in `master`, but something that has to be changed before releasing the next version of Pi-hole.**
---

**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

## 10

---
**Expected behaviour:**

The path for the long term API will not be hard-coded any longer when `FTL v2.13` is released. Hence, the PHP scripts may not be able to find the database file any longer.

**Actual behaviour:**

The path is still hard-coded in PHP, any non-standard location will lead to an error.

**Steps to reproduce:**

Use `development` version of `FTL` and customize the path.

**How to fix:**

Read location of database file from `pihole-FTL.conf`

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

Fix #643 

**How does this PR accomplish the above?:**

Read `FTL`'s config file for a possible custom database location and use this one if applicable

**What documentation changes (if any) are needed to support this PR?:**

This will do everything automatically, no changes required.

### CODE REVIEW

**Comment by DL6ER** [comment]
Tested with specifying
```
DBFILE=/var/log/pihole-FTL.db
```
in `pihole-FTL.conf`. After restarting `FTL`, this new database file was created and contained only the most recent 24 hours which were queryable via the long term statistics part of the web interface afterwards.

File: api_db.php [hunk 1]
```diff
@@ -33,8 +47,14 @@ function SQLite3_connect($trytoreconnect)
...
 
-$db = SQLite3_connect(true);
-
+if(strlen($DBFILE) > 0)
+{
+	$db = SQLite3_connect(true);
+}
+else
+{
+	die("No database available");
```
Comment (Mcat12) [inline api_db.php]: Good checking if the database path exists, but won't it always be set because of the other if/else block?

Comment (DL6ER) [reply api_db.php]: It is possible that `$FTLsettings["DBFILE"]` is set to an empty value (that is a legitime variant of telling `FTL` that you don't want the database) so this case can happen.
