### PR TITLE
Fix sorting of queries with identical timestamps

### LINKED ISSUE #934: Query Log: Wrong sort order (equal timestamp)
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`"Query Log" ("Recent Queries") in the "Pi-hole Admin Console" should show the recent queries in correct sort order.`

**Actual behaviour:**

`The sort order is not correct (or may not be correct) for log entries with the same timestamp.
Especially if you have blocked and non-blocked queries at the same time it's confusing to have the blocked entries (in time) before the non-blocked entries.`

**Steps to reproduce:**

`Do DNS requests and check the result in the Admin Console ("Query Log" / "Recent Queries") and also in the log-file and/or in the database.`
Note: There must be several DNS requests at the same timestamp (the same second).
N.B.: The default sort order for "Recent Queries" is descending by time.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`f2o6gv35po`

**Troubleshooting undertaken, and/or other relevant information:**

- (checked source code).

Note: I saw this wrong sort order also often in the past.

The "problem" is because of just using UNIX timestamps in the log and database.   
UNIX timestamps only have seconds and so they are not very accurate (no fractions of a second, i.e. no milliseconds/nanoseconds).

The query seems to use the timestamp as only sort-criteria.
https://github.com/pi-hole/AdminLTE/blob/f2b2aa42c0b37ab16ada30f0162a14782a82807c/api_db.php#L104 
https://github.com/pi-hole/AdminLTE/blob/f2b2aa42c0b37ab16ada30f0162a14782a82807c/api_db.php#L122

The result for the website will be re-sorted by .js:
https://github.com/pi-hole/AdminLTE/blob/347994db169eb486954cbcff6f62955c77c1db4a/scripts/pi-hole/js/queries.js#L293

[I'm not skilled with web-applications and I hope I've linked to relevant source code.]

---

Let's look to an _example_, to see it more clearly.

In the web interface (with default sort order: descending by time) the _blocked_ entries (`www.akamai.net`) seems to be before the _forwarded_ entries (`akamai.net`).  All entries have the same timestamp ("23:58:08").
Pi-hole - Wrong sort order (Web interface)

In the log file you can see the truth: The forwarded entries are before the blocking entries.
```
# cat /var/log/pihole.log.1 | grep 23:58:0
Apr 28 23:58:08 dnsmasq[719]: query[A] akamai.net from 192.168.1.10
Apr 28 23:58:08 dnsmasq[719]: forwarded akamai.net to 127.0.0.1
Apr 28 23:58:08 dnsmasq[719]: query[A] akamai.net from 192.168.1.10
Apr 28 23:58:08 dnsmasq[719]: forwarded akamai.net to 127.0.0.1
Apr 28 23:58:08 dnsmasq[719]: reply akamai.net is NODATA-IPv4
Apr 28 23:58:08 dnsmasq[719]: query[A] www.akamai.net from 192.168.1.10
Apr 28 23:58:08 dnsmasq[719]: /etc/pihole/regex.list www.akamai.net is 0.0.0.0
Apr 28 23:58:08 dnsmasq[719]: query[A] www.akamai.net from 192.168.1.10
Apr 28 23:58:08 dnsmasq[719]: /etc/pihole/regex.list www.akamai.net is 0.0.0.0
```

Also in the database I can see the _forwarded_ `akamai.net` entries before the _blocked_ `www.akamai.net` entries.
```
sqlite> select * from queries where timestamp = 1556488688 and domain like '%akamai%';
127217|1556488688|1|2|akamai.net|192.168.1.10|127.0.0.1
127218|1556488688|1|2|akamai.net|192.168.1.10|127.0.0.1
127219|1556488688|1|4|www.akamai.net|192.168.1.10|
127220|1556488688|1|4|www.akamai.net|192.168.1.10|
```

---

Possible solutions:
* Use a more precise timestamp.
* Select also the `id` from the database table, pass it thru the API/.js/.php and use the `id` for sorting (only internally/in the background/hidden; it might not be useful to display the `id` on the web-site).

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

Queries with identical timestamps are sorted in the wrong order when looking at the query log data descending. See #934 for further details. This PR fixes #934.

**How does this PR accomplish the above?:**

Modify timestamps during loading to make them non-unique. Our modification is reverted when we convert the UNIX timestamp to a formatted date string. This allows us to fix this issue with

**What documentation changes (if any) are needed to support this PR?:**

None, this PR does not break anything.

### CODE REVIEW

**Comment by DL6ER** [comment]
Opened as draft PR as the code changes need to be repeated for the long-term query table.

File: scripts/pi-hole/js/queries.js [hunk 1]
```diff
@@ -293,18 +293,32 @@ $(document).ready(function() {
...
+                    new_data.push(obj);
+                }
+                return new_data;
+            }
+        },
         "autoWidth" : false,
         "processing": true,
         "order" : [[0, "desc"]],
         "columns": [
-            { "width" : "15%", "render": function (data, type, full, meta) { if(type === "display"){return moment.unix(data).format("Y-MM-DD [<br class='hidden-lg'>]HH:mm:ss z");}else{return data;} }},
```
Comment (Mcat12) [inline scripts/pi-hole/js/queries.js]: Could this render function have instead been modified? When the type is "display", do the division and display the time. Otherwise (for sorting I assume) return the data.

File: scripts/pi-hole/js/db_queries.js [hunk 2]
```diff
@@ -310,13 +310,26 @@ $(document).ready(function() {
...
+            "error": handleAjaxError,
+            "dataSrc": function(data){
+                var new_data = new Array();
+                for(obj of data.data)
+                {
+                    obj[0] *= parseInt(1e6);
+                    obj[0] += dataIndex++;
+                    new_data.push(obj);
+                }
+                return new_data;
```
Comment (Mcat12) [inline scripts/pi-hole/js/db_queries.js]: This could be done more cleanly using [`map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map).

File: scripts/pi-hole/js/db_queries.js [hunk 3]
```diff
@@ -224,6 +224,7 @@ function refreshTableData() {
 
 $(document).ready(function() {
     var status;
+    var dataIndex = 0;
```
Comment (Mcat12) [inline scripts/pi-hole/js/db_queries.js]: This should be moved into the `dataSrc` function.

File: scripts/pi-hole/js/db_queries.js [hunk 4]
```diff
@@ -310,13 +310,17 @@ $(document).ready(function() {
              "<'row'<'col-sm-4'l><'col-sm-8'p>>" +
              "<'row'<'col-sm-12'<'table-responsive'tr>>>" +
              "<'row'<'col-sm-5'i><'col-sm-7'p>>",
-        "ajax": {"url": APIstring, "error": handleAjaxError },
+        "ajax": {
+            "url": APIstring,
+            "error": handleAjaxError,
+            "dataSrc": function(data){ return data.data.map(function(x){ x[0] = x[0]*1e6+(dataIndex++); return x; }); }
```
Comment (Mcat12) [inline scripts/pi-hole/js/db_queries.js]: This should be on multiple lines to make it more readable.

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-4-3-2-release-notes/23852/1
