### PR TITLE
Use gravity updated timestamp from database

### LINKED ISSUE #989: time period since last gravity update is displayd incorrectly (in dev)
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`5`

---
**Expected behaviour:**

Hovering the red tile on the dashboard with the pointer should show the time period since the last gravity update.

**Actual behaviour:**

The displayd time period is not correct, since the period is still calculated from the modification date of /etc/pihole/gravity.list in [`gravity.php`](https://github.com/pi-hole/AdminLTE/blob/devel/scripts/pi-hole/php/gravity.php#L16).

**Steps to reproduce:**

1) checkout **dev** branch
2) hover the red tile on the dashboard with the pointer and notice the shown time period since last update.
3) update the gravity lists (whether via Web interface or CLI)
4) repeat step 2 again and notice that the shown period has not changed.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`-`

**Troubleshooting undertaken, and/or other relevant information:**
 
As I see it is not enough to use the modification date of `/ect/pihole/gravity.db` because it's timestamp also changes after changes are done do the White- or Blacklist.

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

Fix #989 (bug existing only in `development`)

**How does this PR accomplish the above?:**

Use update timestamp added in https://github.com/pi-hole/pi-hole/pull/2903 to display the time gravity was last run (successfully).

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

File: scripts/pi-hole/php/gravity.php [hunk 1]
```diff
@@ -1,51 +1,61 @@
...
+*  This file is copyright under the latest version of the EUPL.
+*  Please see LICENSE file for your rights under this license. */
+
+require "scripts/pi-hole/php/database.php";
+
+function gravity_last_update($raw = false)
+{
+	$db = SQLite3_connect(getGravityDBFilename());
+	$date_file_created_unix = $db->querySingle("SELECT value FROM info WHERE property = 'updated';");
+	if($date_file_created_unix !== false)
```
Comment (Mcat12) [inline scripts/pi-hole/php/gravity.php]: Invert this if statement to reduce nesting
